### PR TITLE
First pass at FST support for flexible orthography, vowel-length neutralization, and isogloss normalization

### PR DESCRIPTION
**Pull request by Lguyogiro**
This PR adds support for flexible orthography and vowel length neutralization, and isogloss normalization on user search input. The implementation only uses FSTs (built with Helsinki Finite State Technology toolkit). The final .hfst files are converted to .att text files which can be parsed by Måns Hulden's attapply.py script (included in this PR). 
The base path to all of this work is `/Users/rpugh/repos/mesolex/lexicon/transformations/transducers`.

New dependencies introduced: `retrie` (`pip install retrie`)

### Basic overview of structure
- `nahuat/fst/input.fst` (defined by `nahuat/lexc/variant.lexc`) maps user input to a pseudo-IPA (henceforth just "IPA") representation. This is the basic flexible orthography that does things like convert from "c" and "qu" to "k". 
- There are three FSTs that operate on the IPA representation and whose outputs are still in IPA.  
- - `nahuat/fst/vln.hfst` (vowel-length neutralization)
- - `nahuat/fst/isoglosses.hfst` (isogloss normalization)
- - `nahuat/fst/flex_w_rules.hfst` (flexible orthography)
- Finally, `nahuat/fst/to_dico.hfst` maps the IPA representation to the orthography used in the azz dictionary.

These fsts are composed 7 different ways to enable all combinations of {flexible orthography, vowel-length neutralization, and isogloss normalization}.

#### Vowel-Length Neutralization

- Vowels {a, e, i, o}, when not followed by a glottal consonant, can be short or long.

#### Isogloss Normalization

- t <=> tl
- e <=> ye // # _
- e <=> i
- [n | m] => null // _ #

#### Flexible Orthgraphy
List of optional rules:
- hu => w // _ V
- uh => w // (C | #)
- c => k // _ Low-vowel
- qu => k
- ç => s
- z => s
- oa <=> owa
- ia <=> iya
- Nasal => null // _ .#.
- Short-vowel => Short-vowel + h // _ C V
- y => i // _ (C | #) e.g. "queny" for "keni" or "yn" for "in"
- w => null // _ #

### Using/integrating the code 
Right now, this code doesn't touch any other part of the codebase (with the exception of the test file I added).  The FSTs can be invoked via Python using fst_handler.py. Given a query term and parameter settings for "flexible orthography", "vln", and "isoglosses", you can generate all possible output forms (list fo strings), or get a regex that matches them (a string), as in the following examples:

```
fst = FSTHandler(get_nahuat_att_file(flex=True, isoglosses=True,  vln=True))

# Generate forms
fst.generate_forms(<word>)

# Get regex
fst.get_pattern(<word>)
```

I've added some basic tests, but they likely should be expanded on.

### CODE REVIEW

**Comment by Lguyogiro** [comment]
sorry about the length of both the changes and the description!

**Comment by nmashton** [comment]
> sorry about the length of both the changes and the description!

I love long PR messages, and I'm thrilled to receive a pull request. :)

**Comment by Lguyogiro** [comment]
I made one more update just now, because I saw that my `fst_handler.py` file was empty. Also I got some feedback about a few changes to make to the transducer.

**Review by nmashton — APPROVED** [review]
@Lguyogiro: this is great. In a local version of your branch, I made a few changes to hook up the transducer to the transformation pipeline system, and it seems to work like a charm.

Rather than delaying your PR any further by making a bunch of change requests and waiting for you to fix them, since my change requests are small and a matter of adding glue code rather than changing anything substantive, I'm going to merge your work into a branch, make the changes, and then get the result into `develop`.

**Pull request merged**
